language: elixir
elixir:
  - '1.8.1'
otp_release:
  - '21.3'
install:
  - mix local.rebar --force;
  - mix local.hex --force
  - mix hex.organization auth smartcolumbus_os --key $HEX_API_KEY 
  - mix deps.get
  - mix format --check-formatted
  - mix credo
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    tags: true
